//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class scraperTable
    {
        public int ID { get; set; }
        public string Symbol { get; set; }
        public decimal currentPrice { get; set; }
        public int changePercent { get; set; }
        public string marketCap { get; set; }
        public System.DateTime dateAndTime { get; set; }
    }
}
